{{- if .Values.authenticatedEmailsFile.enabled }}
{{- if and (.Values.authenticatedEmailsFile.restricted_access) (eq .Values.authenticatedEmailsFile.persistence "secret")  }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app: {{ template "oauth2-proxy.name" . }}
    chart: {{ template "oauth2-proxy.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "oauth2-proxy.fullname" . }}-accesslist
  annotations:
    "helm.sh/resource-policy": keep
data:
  restricted_user_access: {{ .Values.authenticatedEmailsFile.restricted_access | b64enc }}
{{- end }}
{{- end }}
